### PR TITLE
fix(cursor): apply TextStyle inline

### LINKED ISSUE #229: cursor: TextStyle is not applied inline
When the cursor is blinking, the TextStyle is not applied inline. So if it contains padding / borders etc, mayhem ensues.

I have a PR for this.

cc @maaslalani

### PR DESCRIPTION
**Pull request by knz**
Found bug using [catwalk](https://github.com/knz/catwalk).

Fixes #229.

cc @maaslalani

### CODE REVIEW

File: cursor/cursor.go [hunk 1]
```diff
@@ -200,8 +200,9 @@ func (m *Model) SetChar(char string) {
 
 // View displays the cursor.
 func (m Model) View() string {
-	if m.Blink {
-		return m.TextStyle.Render(m.char)
+	style := m.TextStyle.Inline(true)
```
Comment (maaslalani) [inline cursor/cursor.go:203]: I don't think we really need to allocate a variable here (to be fair, I'd guess the Go compiler does optimize this for us), we can use the same return logic as before and add an `Inline(true)` to the style.
